import {BuyListBuilder} from "../../abstract/BuyListBuilder";
import * as admin from "firebase-admin";

export class AutogeneratedBuyListBuilder extends BuyListBuilder {

    constructor(
        private user: admin.firestore.DocumentReference
    ) {
        super()
    }

    buildDateCreation(): void {
        this.buyList.dateCreated = admin.firestore.Timestamp.now()
    }

    buildName(): void {
        this.buyList.name = "Рекомендую купить"
    }

    buildUser(): void {
        this.buyList.user = this.user
    }

}
