import {BuyListBuilder} from "../../abstract/BuyListBuilder";
import * as admin from "firebase-admin";

export class AutogeneratedBuyListBuilder extends BuyListBuilder {

    constructor(
        private user: admin.firestore.DocumentReference
    ) {
        super()
    }

    buildName(): void {
        if (this.buyList === undefined) return;
        this.buyList.name = "Рекомендем купить"
    }

    buildUser(): void {
        if (this.buyList === undefined) return;
        this.buyList.user = this.user
    }

    buildIsHidden(): void {
        if (this.buyList === undefined) return;
        this.buyList.isHidden = true
    }

}
