import {DocumentSnapshot} from "firebase-functions/lib/providers/firestore";
import {IBAutoGeneratedShoppingListId} from "../../classses/builders/indetefires/IBAutoGeneratedShoppingListId";
import {IdentifierCreator} from "../../classses/creators/IdentifierCreator";
import * as admin from "firebase-admin";
import {FirestoreCollection} from "../../enums/FirestoreCollection";
import {deserialize, serialize} from "typescript-json-serializer";
import {Inventory} from "../../classses/model/Inventory";
import {InventoryEndsNotifBuilder} from "../../classses/builders/notifications/InventoryEndsNotifBuilder";
import {NotificationCreator} from "../../classses/creators/NotificationCreator";
import {SLIBFromInventory} from "../../classses/builders/shoppingListItems/SLIBFromInventory";
import {ShoppingListItemCreator} from "../../classses/creators/ShoppingListItemCreator";
import {Helper} from "../../classses/helpers/Helper";

export class InventoryFunctions {

    updateCountInParentObjects(snapshot: DocumentSnapshot, count: number): Promise<any> | void {
        console.info("Inventory count update started");
        const item = deserialize(snapshot.data(), Inventory);
        const parentRefs = item.getParentRefs();
        const promises = parentRefs.map(ref => {
            console.info("Updated inventories count in '" + ref.path + "' to '" + count + "'");
            return Helper.firestore().incrementField(ref, "inventories_count", count);
        });
        return Promise.all(promises);
    }

    incrementCountInParentObjects(snapshot: DocumentSnapshot) {
        return this.updateCountInParentObjects(snapshot, 1)
    }

    decrementCountInParentObjects(snapshot: DocumentSnapshot) {
        return this.updateCountInParentObjects(snapshot, -1)
    }

    /** Изменение количиства инвентаря в связанных списках **/

    /**
     * Обновляет счетчик количества инветаря в связванных списках
     * @param before
     * @param after
     */
    updateInventoryInListCount(before: DocumentSnapshot, after: DocumentSnapshot) {
        const itemBefore = deserialize(before.data(), Inventory);
        const itemAfter = deserialize(after.data(), Inventory);
        if (itemBefore.inventoryList === itemAfter.inventoryList) return Promise.resolve();
        return Promise.all([
            this.decrementInventoryInListCount(before),
            this.incrementInventoryInListCount(after)
        ])
    }

    /**
     * Увеличивает счетчик количества инвентаря в списке на 1
     * @param snapshot
     */
    incrementInventoryInListCount(snapshot: DocumentSnapshot) {
        const item = deserialize(snapshot.data(), Inventory);
        if (item.inventoryList === undefined) return Promise.resolve();
        return Helper.firestore().incrementField(item.inventoryList, "inventories_count")
    }

    /**
     * Уменьшает счетчик количества инвентаря в списке на 1
     * @param snapshot
     */
    decrementInventoryInListCount(snapshot: DocumentSnapshot) {
        const item = deserialize(snapshot.data(), Inventory);
        if (item.inventoryList === undefined) return Promise.resolve();
        return Helper.firestore().decrementField(item.inventoryList, "inventories_count")
    }

    /**
     * Удаляет все связанные с инвентарём автосгененрированные покупки
     * @param snapshot
     */
    deleteRelatedShoppingListItems(snapshot: DocumentSnapshot) {
        const inventory = deserialize(snapshot.data(), Inventory);
        const inventoryRef = snapshot.ref;

        const uid = inventory.user!.id;

        const autoGeneratedShoppingListIdBuilder = new IBAutoGeneratedShoppingListId(uid);
        const idCreator = new IdentifierCreator(autoGeneratedShoppingListIdBuilder);

        idCreator.construct();

        const autoGeneratedShoppingListId = idCreator.get();
        const autoGeneratedShoppingListRef = admin.firestore().collection(FirestoreCollection.BuyLists).doc(autoGeneratedShoppingListId);

        const query = admin.firestore()
            .collection(FirestoreCollection.Buys)
            .where("list", "==", autoGeneratedShoppingListRef)
            .where("related_object", "==", inventoryRef);
        return Helper.firestore().deleteAllFilesInQuery(query);
    }

    /***
     * Добавляет уведомление о замене инвентаря
     * @param snapshot
     */
    createOnInventoryEndsNotification(snapshot: DocumentSnapshot): Promise<any> {
        const inventory = deserialize(snapshot.data(), Inventory);
        const uid = inventory.user!.id;

        if (inventory.nextReplacementDate === undefined) {
            return Promise.resolve();
        }

        const notificationBuilder = new InventoryEndsNotifBuilder(uid, snapshot.ref, inventory);
        const notificationCreator = new NotificationCreator(notificationBuilder);

        const notification = notificationCreator.construct().get();

        return admin.firestore().collection(FirestoreCollection.Notifications).doc().create(serialize(notification));
    }

    /**
     * Добавляет покупку если установленна дата замены
     * @param snapshot
     */
    createShoppingListItem(snapshot: DocumentSnapshot): Promise<any> {
        const inventory = deserialize(snapshot.data(), Inventory);
        const uid = inventory.user!.id;

        if (inventory.nextReplacementDate === undefined) {
            return Promise.resolve();
        }

        const userLink = admin.firestore().collection(FirestoreCollection.Users).doc(uid);

        const shoppingListIdbBuilder = new IBAutoGeneratedShoppingListId(uid);
        const identifierCreator = new IdentifierCreator(shoppingListIdbBuilder);

        identifierCreator.construct();

        const shoppingListId = identifierCreator.get();

        const shoppingListLink = admin.firestore().collection(FirestoreCollection.BuyLists).doc(shoppingListId);

        const shoppingListItemBuilder = new SLIBFromInventory(inventory, snapshot.ref, shoppingListLink, userLink);
        const shoppingListItemCreator = new ShoppingListItemCreator(shoppingListItemBuilder);

        shoppingListItemCreator.construct();

        const shoppingListItem = shoppingListItemCreator.get();

        return admin.firestore().collection(FirestoreCollection.Buys).doc().create(serialize(shoppingListItem))
    }

}
