import {ShoppingListItemBuilder} from "../../abstract/ShoppingListItemBuilder";
import {Inventory} from "../../model/Inventory";
import * as admin from "firebase-admin";

export class SLIBFromInventory extends ShoppingListItemBuilder {

    constructor(
        private inventory: Inventory,
        private inventoryLink: admin.firestore.DocumentReference,
        private autoGeneratedShoppingListLink: admin.firestore.DocumentReference,
        private userLink: admin.firestore.DocumentReference
    ) {
        super()
    }

    buildCount(): void {
        this.shoppingListItem.count = this.inventory.count
    }

    buildDateCreated(): void {
        this.shoppingListItem.dateCreated = admin.firestore.Timestamp.now()
    }

    buildDateToBuy(): void {
        const dateToBuyMills = this.inventory.nextReplacementDate.toMillis() - 2 * 24 * 3600 * 1000;
        this.shoppingListItem.dateToBuy = admin.firestore.Timestamp.fromMillis(dateToBuyMills);
    }

    buildDescription(): void {
        this.shoppingListItem.description = this.inventory.description;
    }

    buildIsDone(): void {
        this.shoppingListItem.isDone = false;
    }

    buildList(): void {
        this.shoppingListItem.list = this.autoGeneratedShoppingListLink
    }

    buildName(): void {
        this.shoppingListItem.name = `Купить "${this.inventory.name}" для замены`;
    }

    buildHousing(): void {
        this.shoppingListItem.housing = this.inventory.housing
    }

    buildUser(): void {
        this.shoppingListItem.user = this.userLink
    }

    buildRelatedObject(): void {
        this.shoppingListItem.relatedObject = this.inventoryLink
    }

}
