import {ShoppingListBuilder} from "../../abstract/ShoppingListBuilder";
import * as admin from "firebase-admin";

export class AutogeneratedShoppingListBuilder extends ShoppingListBuilder {

    constructor(
        private user: admin.firestore.DocumentReference
    ) {
        super()
    }

    buildName(): void {
        this.shoppingList.name = "Рекомендем купить"
    }

    buildUser(): void {
        this.shoppingList.user = this.user
    }

    buildIsHidden(): void {
        this.shoppingList.isHidden = true
    }

}
