import {IdentifierBuilder} from "../../abstract/IdentifierBuilder";

export class IBAutoGeneratedShoppingListId extends IdentifierBuilder {

    constructor(
        private uid: string
    ) {
        super()
    }

    build(): void {
        this.id = `shopping_list_${this.uid}_autogenerated`
    }
}
